### PR TITLE
Add `QuantumOpticsSystem` for creating `QuantumSystem`

### LINKED ISSUE #85: [Feature]: interface with QuantumOptics.jl
### Feature Description

It would be great to have the functionality to build `QuantumSystem`s using [operators](https://docs.qojulia.org/quantumobjects/operators/) from QuantumOptics.jl. This should be a very simple PR that adds a dependency for QuantumOptics and creates a method for [`QuantumSystem`](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/86ae355abff314b4dc6ac98591b51ae626fdac71/src/quantum_systems.jl#L102). 

#### Implementation Guidelines

- A file should be added to the directory [`src/quantum_system_templates`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/src/quantum_system_templates), matching the style of the files therein.
- Add a doc script to the folder [`docs/literate/man`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/docs/literate/man)
  - see the [Literate.jl](https://github.com/fredrikekre/Literate.jl) docs and the other scripts in the `docs/literate` folder
- Add a file to [`test`](https://github.com/aarontrowbridge/QuantumCollocation.jl/tree/main/test) with some simple tests for the functions exported
 

### Importance

2

### What does this feature affect?

- [X] quantum system construction
- [ ] problem setup
- [ ] problem solution
- [ ] problem performance
- [ ] solution analysis
- [ ] plotting
- [ ] documentation
- [ ] tests
- [ ] other (please specify below)

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maxwell04-wq**
Fixes #85. 

- Added a function `QuantumOpticsSystem` for creating a system using QuantumOptics
- Extended a new `QuantumSystem` function for compatibility with `QuantumOpticsSystem`
- Added tests for `QuantumOpticsSystem`

### CODE REVIEW

**Comment by maxwell04-wq** [comment]
@aarontrowbridge I believe that the PR is ready to review now. I have not added the docs yet; I need some time to document it.

**Comment by aarontrowbridge** [comment]
let's see if the CI runs

**Comment by maxwell04-wq** [comment]
@aarontrowbridge can you confirm whether I need to create the `QuantumSystem` object using `QuantumOpticsBase.Operator` as mentioned in the PR or using `QuantumObject{SparseMatrixCSC, ...}` object as discussed in the call? I have implemented them both, but the latter is commented out.
Also, can you please review it before day end so that I can make any major changes before the end of UnitaryHack if necessary?

**Comment by aarontrowbridge** [comment]
this looks good thanks!

**Comment by maxwell04-wq** [comment]
Awesome! This was fun; thanks for all the help:)

**Pull request merged**
