### PR TITLE
Sample Based Robust Control

### PR DESCRIPTION
**Pull request by Fe-r-oz**
Resolving https://github.com/aarontrowbridge/QuantumCollocation.jl/issues/89

Preparing the initial structure of the notebook with proper documentation.

### CODE REVIEW

**Comment by Fe-r-oz** [comment]
Progress Update:

- Created Ensemble of Quantum Systems, Sampled Via Normal Distribution
- Created UnitarySmoothPulseProblem for each quantum system
- Creating Direct Sum Problems from above problems (2), Trying to solve this

In the meantime, I am reading the documentation for [add_suffix](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/main/src/direct_sums.jl) and learning about how manually recreating the NamedTrajectory container along with 3. Glue the trajectory together with the right dynamics.

Thanks a lot @andgoldschmidt for  https://github.com/aarontrowbridge/QuantumCollocation.jl/issues/89#issuecomment-2143541610! I followed your comments and created the initial notebook. I have incorporated step 1 and step 2 from your comments at the moment to get started. 

Kindly please download the notebook and please let me know how I am doing? Thanks!

**Comment by Fe-r-oz** [comment]
Progress Update:
- Created the Draft for function` SampleBasedControlProblem` based on the suggested implementation guidelines in step 3 and step 4. I am passing ensemble of quantum systems to this function after sampling.
-  I have utilized the `add_suffix` in a way that is used in the [UnitaryDirectSumProblem](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/main/src/problem_templates/unitary_direct_sum_problem.jl).  
- I get this error when I try to  solve!: `ArgumentError: Provided trajectories must have fixed timesteps.` This is because of the way I am merging suffix trajectories using `direct_sum`. I would be grateful if you have a look at the draft function` SampleBasedControlProblem` from the notebook!

Anyhow, 
> Kindly please download the notebook and please let me know how I am doing? Thanks a lot!

In the meantime, I will try to read the [UnitaryDirectSumProblem](https://github.com/aarontrowbridge/QuantumCollocation.jl/blob/main/src/problem_templates/unitary_direct_sum_problem.jl) for further clarification.

**Comment by Fe-r-oz** [comment]
Progress Update:

- Completed step 3: Making the integrators we need for each quantum system in our ensemble using `for loop` and `add_suffix`! 

What's left is step 2: I did create Named Tragectories for all the quantum systems in the ensemble using add_suffix . But having some trouble in combining them via direct sum and add suffix to get one shared control.

**Comment by andgoldschmidt** [comment]
Hi @Fe-r-oz, closing this PR until it is ready to be reviewed by a maintainer. In the meantime, please use the issues page to keep up our discussion!

**Pull request closed without merging**
